version: v0.1
testName: Exercise_Page_Tests
testPlan: LoadTest_ExercisePage.jmx
description: Load test website exercise page
engineInstances: 1
configurationFiles:
  - 'SampleData-Nutrition.csv'
failureCriteria:
  - avg(response_time_ms) > 20000
  - percentage(error) > 20
#env:
#  - name: my-variable
#    value: my-value
#secrets:
#  - name: my-secret
#    value: https://MercuryHealth.vault.azure.net/secrets/MySecret
#
