version: v0.1
testName: 'Mercury Health API Tests'
testPlan: LoadTest_HomePage.jmx
description: Load test website home page
engineInstances: 1
configurationFiles:
  - 'SampleData-Nutrition.csv'
failureCriteria:
  - avg(response_time_ms) > 10000
  - percentage(error) > 100
#env:
#  - name: my-variable
#    value: my-value
#secrets:
#  - name: my-secret
#    value: https://MercuryHealth.vault.azure.net/secrets/MySecret
#
