version: v0.1
testName: MercuryHealth_API_Tests
testPlan: LoadTest_HomePage.jmx
description: Load test website home page
engineInstances: 1
configurationFiles:
  - 'SampleData-Nutrition.csv'
failureCriteria:
  - avg(response_time_ms) > 10000
  - percentage(error) > 100
#env:
#  - name: my-variable
#    value: my-value
#secrets:
#  - name: my-secret-ClientId
#    value: https://kv-fq3ruuhxgjony.vault.azure.net/secrets/ClientId/f1526569a9524945a3632247f4fa862c
#  - name: my-secret-SubscriptionKey
#    value: https://kv-fq3ruuhxgjony.vault.azure.net/secrets/SubscriptionKey/f1526569a9524945a3632247f4fa862c
#
