# This is a basic workflow to help you get started with Actions
name: deploy-main-hdc

###################################################################
# Triggers - Controls when the action will run.
###################################################################
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

###################################################################
# Environment Variables
###################################################################
env:
  # Path to the solution file relative to the root of the project.
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  dotnet_version: '6.x.x'
  Azure_Resource_GroupName: 'rg-MercuryHealth'
  Azure_Resource_GroupLocation: 'eastus2'
  
jobs:
  Build_Application:
    runs-on: ubuntu-latest
    name: 'Build Application'

    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ###########################################
      # Build App
      ###########################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet_version }}

      # Generate Build Assembly Version based on Date/Time
      - name: Generate Build Assembly Version
        uses: Azure/powershell@v1
        id: setBuildNumber
        env:
          POWERSHELL_TELEMETRY_OPTOUT: 1
        with:
          inlineScript: ./GenerateVersionNumber.ps1
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: '3.4.0'
          # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
          errorActionPreference: continue
          
      # Run dotnet build and publish
      - name: dotnet build unit test and publish
        run: |
          dotnet restore
          dotnet build MercuryHealth.Web/MercuryHealth.Web.csproj --configuration ${{ env.buildConfiguration }} --no-restore
          dotnet publish MercuryHealth.Web/MercuryHealth.Web.csproj --configuration ${{ env.buildConfiguration }} -o './web' /p:FileVersion="${{ steps.setBuildNumber.outputs.BuildNumber }}" /p:Version="${{ steps.setBuildNumber.outputs.BuildNumber }}" /p:AssemblyVersion="${{ steps.setBuildNumber.outputs.BuildNumber }}"
          #dotnet build MercuryHealth.API/MercuryHealth.API.csproj --configuration ${{ env.buildConfiguration }} --no-restore
          #dotnet publish MercuryHealth.API/MercuryHealth.API.csproj --configuration ${{ env.buildConfiguration }} -o './api' /p:FileVersion="${{ steps.setBuildNumber.outputs.BuildNumber }}" /p:Version="${{ steps.setBuildNumber.outputs.BuildNumber }}" /p:AssemblyVersion="${{ steps.setBuildNumber.outputs.BuildNumber }}"
          dotnet build MercuryHealth.UITests/MercuryHealth.UITests.csproj --configuration ${{ env.buildConfiguration }} --no-restore
          dotnet publish MercuryHealth.UITests/MercuryHealth.UITests.csproj --configuration ${{ env.buildConfiguration }} -o './uitests'
          dotnet build MercuryHealth.FunctionApp/MercuryHealth.FunctionApp.csproj --configuration ${{ env.buildConfiguration }} --no-restore
          dotnet publish MercuryHealth.FunctionApp/MercuryHealth.FunctionApp.csproj --configuration ${{ env.buildConfiguration }} -o './functionapp'
      - name: dotnet retore database
        run: dotnet restore MercuryHealth.Database/MercuryHealth.Database.csproj
      - name: dotnet build database
        run: dotnet build MercuryHealth.Database/MercuryHealth.Database.csproj --configuration ${{ env.buildConfiguration }} --no-restore --output './database'

      ###########################################
      # Run Unit Tests
      ###########################################
      - name: dotnet run unit tests
        run:  dotnet test MercuryHealth.UnitTests/MercuryHealth.UnitTests.csproj

      ###########################################
      # Upload Artifacts
      ###########################################
      - name: Upload Build Artifacts-Website
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.Website
          path: ${{ github.workspace }}/web

      - name: Upload Build Artifacts-FunctionApp
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.FunctionApp
          path: ${{ github.workspace }}/functionapp

      - name: Upload Build Artifacts-Database
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.Database
          path: ${{ github.workspace }}/database

      - name: Upload Build Artifacts-UI Tests
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.UITests
          path: ${{ github.workspace }}/uitests

      - name: Upload Build Artifacts-UI Tests runsettings file
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.UITests
          path: ${{ github.workspace }}/MercuryHealth.UITests/MercuryHealthTests.runsettings

      - name: Upload Build Artifacts-UI Tests runsettings Transform PS file
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.UITests
          path: ${{ github.workspace }}/MercuryHealth.UITests/TransformRunSettings.ps1
          
      - name: Upload Infrastucture Files
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.IaC
          path: ${{ github.workspace }}/MercuryHealth.IaC/*.*

      - name: Upload Load Test Files
        #if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: MercuryHealth.LoadTests
          path: ${{ github.workspace }}/MercuryHealth.LoadTests/*.*

###########################################
# Deploy to Environments
###########################################
  dev:
    #if: contains(github.event_name, 'push')
    needs: Build_Application
    uses: ./.github/workflows/deploy-environment-hdc.yml
    with:
      resource-group-base-name: 'rg-hdc-demo'
      environment-suffix: 'dev'
      resource-group-location: 'eastus2'
      approval-required: true
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
